// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATE3vTLA1pJ_BzmmWtIynx1xq2QJNnQOk',
    appId: '1:617989222905:web:e00cde3b2a9621f87b0d28',
    messagingSenderId: '617989222905',
    projectId: 'couplit-65965',
    authDomain: 'couplit-65965.firebaseapp.com',
    storageBucket: 'couplit-65965.firebasestorage.app',
    measurementId: 'G-ZZJKFKHQ3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWBfwY0z2thToFuk84jeydELpBeUpm5U0',
    appId: '1:617989222905:android:9916c2c1d25d4b8c7b0d28',
    messagingSenderId: '617989222905',
    projectId: 'couplit-65965',
    storageBucket: 'couplit-65965.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHg1ypZZzyxZyq8oxzKJIsrbj-HfSE3eE',
    appId: '1:617989222905:ios:554a4bbdea8c31a87b0d28',
    messagingSenderId: '617989222905',
    projectId: 'couplit-65965',
    storageBucket: 'couplit-65965.firebasestorage.app',
    iosBundleId: 'com.example.couplit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHg1ypZZzyxZyq8oxzKJIsrbj-HfSE3eE',
    appId: '1:617989222905:ios:554a4bbdea8c31a87b0d28',
    messagingSenderId: '617989222905',
    projectId: 'couplit-65965',
    storageBucket: 'couplit-65965.firebasestorage.app',
    iosBundleId: 'com.example.couplit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATE3vTLA1pJ_BzmmWtIynx1xq2QJNnQOk',
    appId: '1:617989222905:web:ce5cadf481de656d7b0d28',
    messagingSenderId: '617989222905',
    projectId: 'couplit-65965',
    authDomain: 'couplit-65965.firebaseapp.com',
    storageBucket: 'couplit-65965.firebasestorage.app',
    measurementId: 'G-N032VF6S2G',
  );
}